### PR TITLE
Fix: no longer overriding blink-cmp per_filetype sources

### LINKED ISSUE #459: 🐞 Bug: Markview overrides user's blink-cmp per_filetype source completions
### 🤖 Which branch are you using?

- [ ] dev
- [x] main

### 📜 Issue description:

I noticed this issue while trying to register a [dictionary source](https://github.com/archie-judd/blink-cmp-words) to [blink-cmp](https://github.com/saghen/blink.cmp) for my markdown writings. If I configure a new provider on [`sources.per_filetype`](https://cmp.saghen.dev/configuration/sources.html#providers) for the markdown filetype (e.g. `source.filetype.markdown = "dicitonary"`), my new provider will not load, and instead my default providers will be loaded alongside markview's provider.

## The cause

I believe the issue is caused by the [register_blink_source](https://github.com/OXY2DEV/markview.nvim/blob/03fe3f42093d47a8536276f682cf057f8c14033b/lua/markview/integrations.lua#L3) function. It [overrides the user's per_filetype definitions](https://github.com/OXY2DEV/markview.nvim/blob/03fe3f42093d47a8536276f682cf057f8c14033b/lua/markview/integrations.lua#L40) with the user's default providers, which is incorrect behavior.

## Proposed solutions

- Write a smarter integration function, that properly merges the user's per_filetype configuration with markview's source.
- Add an explicit option to disable markview's integrations and allow users to manually add markview's sources.

## Current Workarounds

Right now, setting `vim.g.markview_blink_loaded = true` before loading `markview` will prevent it from overriding blink-cmp's sources. It's then possible to manually register [markview's provider](https://github.com/OXY2DEV/markview.nvim/blob/03fe3f42093d47a8536276f682cf057f8c14033b/lua/blink-markview.lua). This will preserve markview's provider and still load my own providers. Example:

```lua
vim.g.markview_blink_loaded = true
require("blink.cmp").setup({
  sources = {
    default = { "lsp", "path", "snippets", "buffer" },
    per_filetype = {
      markdown = { inherit_defaults = false, "markview", "thesaurus" },
    },
    providers = {
      markview = { module = "blink-markview" },
      dictionary = { module = "blink-cmp-words.dictionary" },
    },
  },
})
```

### 📑 Reproduction steps:

1. Open neovim on a markdown file (`nvim potato.md`)
2. Write any english word (e.g. `tomato`)
3. `blink-cmp` should be triggered with definitions of the word like such:

Image

Instead, it shows nothing:

Image

### 💻 Minimal init:

```lua
vim.env.LAZY_STDPATH = ".repro"
load(vim.fn.system("curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua"))()

require("lazy.minit").repro({
  spec = {
    {
      "nvim-treesitter/nvim-treesitter",
      build = ":TSUpdate",

      ensure_installed = { "html", "latex", "markdown", "markdown_inline", "typst", "yaml" }
    },
    {
      "OXY2DEV/markview.nvim",
      -- branch = "dev",
      lazy = false
    },
    {
      enabled = true,
      'saghen/blink.cmp',
      dependencies = {
        'archie-judd/blink-cmp-words',
      },
      opts = {
        sources = {
          default = { 'buffer' },
          per_filetype = { markdown = { "dictionary" } },
          providers = {
            dictionary = {
              module = "blink-cmp-words.dictionary",
            }
          }
        },
      },
    },
  },
});
```

### 📜 Logs:

```
LOG |                       fn()                       | Registered integration:  blink.cmp 
LOG |   markview/autocmds.lua => optionSet() -> wrap   | Option changed.
LOG | markview/autocmds.lua => optionSet() -> filetype | Option changed.
```

### Neovim version:

NVIM v0.11.5

### ✅ Expected behavior:

Markview should preserve the `per_filetype` sources instead of overriding them with the default sources.

### PR DESCRIPTION
**Pull request by Jeansidharta**
Closes #459 

I went ahead and wrote a smarter integration function for blink-cmp. It basically checks if the user provided a per_filetype configuration, and if they did, extend that instead of the defaults. It seems to be working in my tests.

This is just a quick and dirty solution that I wrote to fix my own workflow. Let me know if there are any changes needed to fix this, or if this solution is not appropriate.

### CODE REVIEW

**Comment by OXY2DEV** [comment]
@Jeansidharta, I have tweaked the PR a bit. Can you check if it's working correctly on your end?

File: lua/markview/integrations.lua [hunk 1]
```diff
@@ -17,6 +17,43 @@ integrations.register_blink_source = function ()
...
+
+		if type(config) == "table" and vim.islist(config) then
+			---@cast config table
+			if vim.list_contains(config, "markview") then
+				-- `markview` is already used as a source.
+				return;
+			end
+
+			-- If the config sources is a list we extend the list of sources.
+			blink_config.sources.per_filetype[filetype] = vim.list_extend(config, { "markview" });
```
Comment (Jeansidharta) [inline lua/markview/integrations.lua]: This is a mistake I also made in my original implementation, and just caught it now:

`vim.list_extend` modifies the list in place. Since this `if` branch essentially asserts that we're dealing with the `default` sources key, we're essentially appending the `markview` source to the default list, and copying  that list to the `per_filetype.markdown` sources, which is incorrect behavior. This means the `markview` source will be loaded on any filetype, not just markdowns.

File: lua/markview/integrations.lua [hunk 2]
```diff
@@ -17,6 +17,43 @@ integrations.register_blink_source = function ()
 		ignore_enable = true
 	});
 
+	--- Dynamic filetype.
+	---@param filetype string
+	---@param config table | fun(): table See |blink-cmp-config-sources|.
+	local function handle_filetype(filetype, config)
+		---|fS
+
+		if type(config) == "table" and vim.islist(config) then
```
Comment (Jeansidharta) [inline lua/markview/integrations.lua]: It turns out that `per_filetype[filetype]` can be something like `{ inherit_defaults = false, "buffer" }`. The `inherit_defaults` key makes it so `vim.islist(config)` is `false`. This means the code will later assume this is a function and try to call it, which will obviously fail.

Comment (Jeansidharta) [reply lua/markview/integrations.lua]: Relevant config link:

https://cmp.saghen.dev/configuration/sources.html#providers

**Comment by Jeansidharta** [comment]
@OXY2DEV I just pushed a [new commit](https://github.com/OXY2DEV/markview.nvim/pull/460/commits/99fccaa4ae68ddea330a89a37326ef9237744a91) so it's easier for you to review. I believe this would fix the two problems I brought up earlier.

After this commit, it seems to be working flawlessly. I tested with my own config, and with some other variations that I could think of.

~My only concern is that the output of `:BlinkCmp status` is showing the `markview` source as disabled, and I'm not entirely sure what the markview source provides, so I'm not sure if it's working right. The output of `:BlinkCmp status` also says that disabled sources might still be working if they're loaded dynamically, so it might be all good.~

Nervermind my last concern. I just checkout the [source code](https://github.com/OXY2DEV/markview.nvim/blob/main/lua/blink-markview.lua#L57) for the completions logic and figured out what it does (pretty neat, actually). Just tested on my end and the provider seems to be working after my changes

image

And it also shows my `thesaurus` provider :smile: 

image
